# Generated by Django 3.1.7 on 2021-03-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghostpost',
            name='total_votes',
        ),
    ]
